-- File: src/main/resources/db/migration/V1__initialize_db.sql
CREATE TABLE employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255),
   name VARCHAR(255), -- Changed from full_name to name
   salary BIGINT,
   CONSTRAINT pk_employee PRIMARY KEY (id)
);

ALTER TABLE employee ADD CONSTRAINT uc_employee_email UNIQUE (email);